name: '[PRN] Quality Engineering'

on:
  pull_request_target:
    branches:
      - main
      - master
      - release/v*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  quality-engineering:
    name: QE
    uses: vtex-apps/usqa/.github/workflows/quality-engineering.yml@ENGINEERS-748-fix-github-deprecated-warn
    with:
      nodeLint: true
      nodeSonar: true
      nodeSonarProjectKey: vtex-apps_cy-runner
      nodeSonarOrganization: vtex-apps
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
      
